# Generated by Django 5.1.3 on 2024-12-03 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coachingrequest_coaching_niche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('sessions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('featured', models.BooleanField(default=False, help_text='Mark this plan as featured.')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='coachingrequest',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaching_requests', to='core.pricingplan'),
        ),
    ]
