# Generated by Django 5.1.3 on 2024-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coachingrequest_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingrequest',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
