# Generated by Django 5.1.3 on 2024-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coachingrequest_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='We invest in the world’s potential', max_length=255, verbose_name='Hero Title')),
                ('hero_description', models.TextField(default='We focus on markets where technology, innovation, and capital can unlock long-term value and drive economic growth.', verbose_name='Hero Description')),
                ('about_title', models.CharField(default='About', max_length=255, verbose_name='About Title')),
                ('about_description', models.TextField(default='Ex cumque tempore....', verbose_name='About Description')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='home_images/', verbose_name='About Image')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
    ]
