# Generated by Django 5.1.3 on 2024-12-19 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
