# Generated by Django 5.1.3 on 2024-12-24 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pricingplan_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrequest',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="يجب إدخال رقم الهاتف بالتنسيق التالي: '+999999999'. يُسمح بإدخال ما يصل إلى 15 رقمًا.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
    ]
