# Generated by Django 5.1.3 on 2024-12-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_coachingrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrequest',
            name='referral_source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('other', 'Other')], max_length=10, verbose_name='Referral Source'),
        ),
    ]
