# Generated by Django 5.1.3 on 2024-12-31 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_coachingrequest_referral_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrequest',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="أدخل رقم الهاتف بالتنسيق الدولي: '+رمز الدولةرقم الهاتف'.", regex='^\\+\\d{9,15}$')], verbose_name='Phone'),
        ),
    ]
