# Generated by Django 5.1.3 on 2025-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_certification_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
