# Generated by Django 5.1.3 on 2025-04-24 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_pricingplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
